yellow:
  styles:
    icon:
      - color: 'rgba(var(--color-yellow),1)'
    label:
      - color: 'rgba(var(--color-yellow-text),1)'
    name:
      - color: 'rgba(var(--color-yellow-text),1)'
    img_cell:
      - background-color: 'rgba(var(--color-yellow), 0.2)'
yellow_on:
  state:
    - styles:
        icon:
          - color: 'rgba(var(--color-yellow),1)'
        label:
          - color: 'rgba(var(--color-yellow-text),1)'
        name:
          - color: 'rgba(var(--color-yellow-text),1)'
        img_cell:
          - background-color: 'rgba(var(--color-yellow), 0.2)'
      value: 'on'
      id: 'on'
yellow_off:
  state:
    - styles:
        icon:
          - color: 'rgba(var(--color-yellow),1)'
        label:
          - color: 'rgba(var(--color-yellow-text),1)'
        name:
          - color: 'rgba(var(--color-yellow-text),1)'
        img_cell:
          - background-color: 'rgba(var(--color-yellow), 0.2)'
      value: 'off'
      id: 'off'