custom_washer_state_job_state_grid_item_list:
    styles:
      card:
        - box-shadow: none
        - padding: 0px
        - border-radius: 'var(--border-radius)'
        - pointer-events: none
        - background-color: 'rgba(var(--color-theme), 0.05)'
        - justify-items: center
      grid:
        - grid-template-areas: '"item1 item2 item3 item4 item5"'
        - grid-template-columns: 1fr 1fr 1fr 1fr 1fr
        - grid-template-rows: min-content
        - column-gap: 7px
        - justify-items: center
      img_cell:
        - justify-items: center
custom_washer_state_grid_job_state_item_list_items:
    show_icon: true
    show_name: false
    size: 20px
    tap_action:
      action: none
    styles:
      card:
        - box-shadow: none
        - padding: 0px
        - border-radius: 50%
        - place-self: center
        - height: 42px
        - width: 42px
        - pointer-events: auto
        - background-color: transparent
      grid:
        - grid-template-areas: '"i"'
      icon:
        - color: var(--google-grey)
custom_washer_state_grid_state_item_list:
  styles:
    card:
      - box-shadow: none
      - padding: 0px
    grid:
      - grid-template-areas: '"item1 item2"'
      - grid-template-columns: 1fr 1fr
      - grid-template-rows: min-content
      - column-gap: 7px
custom_washer_state_grid:
  styles:
    card:
      - border-radius: 'var(--border-radius)'
      - box-shadow: 'var(--box-shadow)'
      - padding: 12px
    grid:
      - grid-template-areas: '"item1" "item2"'
      - grid-template-columns: 1fr
      - grid-template-rows: min-content  min-content
      - row-gap: 12px
  custom_fields:
    item1:
      card:
        type: custom:button-card
        template: custom_washer_state_grid_state_item_list
        custom_fields:
          item1:
            card:
              type: custom:button-card
              template:
                - icon_info
              entity: '[[[ return variables.ulm_custom_washer_grid_machine_state ]]]'
              icon: 'mdi:washing-machine'
              name: Wasmachine
              tap_action:
                action: more-info
              label: 'Niet actief'
              state:
                - value: 'on'
                  label: 'Actief'
                  styles:
                    icon:
                      - color: 'rgba(var(--color-blue), 1)'
                    img_cell:
                      - background-color: 'rgba(var(--color-blue), 0.2)'
          item2:
            card:
              type: conditional
              conditions:
                - entity: '[[[ return variables.ulm_custom_washer_grid_machine_state ]]]'
                  state: 'on'
              card:
                type: custom:button-card
                template:
                  - icon_info
                entity: '[[[ return variables.ulm_custom_washer_grid_completion_timestamp ]]]'
                icon: 'mdi:progress-clock'
                name: 'Resterend'
                tap_action:
                  action: none
                label: '[[[ return states[variables.ulm_custom_washer_grid_completion_timestamp].state ]]]'
    item2:
      card:
        type: custom:button-card
        template: custom_washer_state_job_state_grid_item_list
        custom_fields:
          item1:
            card:
              type: custom:button-card
              icon: mdi:scale
              template: custom_washer_state_grid_job_state_item_list_items
              entity: '[[[ return variables.ulm_custom_washer_grid_job_state ]]]'
              state:
                - value: 'weightSensing'
                  styles:
                    icon:
                      - transform: scale(1.2)
                      - color: black
                    card:
                      - background-color: 'white'
          item2:
            card:
              type: custom:button-card
              icon: mdi:waves
              template: custom_washer_state_grid_job_state_item_list_items
              entity: '[[[ return variables.ulm_custom_washer_grid_job_state ]]]'
              state:
                - value: 'wash'
                  styles:
                    icon:
                      - transform: scale(1.2)
                      - color: black
                    card:
                      - background-color: 'white'
          item3:
            card:
              type: custom:button-card
              icon: mdi:water
              template: custom_washer_state_grid_job_state_item_list_items
              entity: '[[[ return variables.ulm_custom_washer_grid_job_state ]]]'
              state:
                - value: 'rinse'
                  styles:
                    icon:
                      - transform: scale(1.2)
                      - color: black
                    card:
                      - background-color: 'white'
          item4:
            card:
              type: custom:button-card
              icon: mdi:fan
              template: custom_washer_state_grid_job_state_item_list_items
              entity: '[[[ return variables.ulm_custom_washer_grid_job_state ]]]'
              state:
                - value: 'spin'
                  styles:
                    icon:
                      - transform: scale(1.2)
                      - color: black
                    card:
                      - background-color: 'white'
          item5:
            card:
              type: custom:button-card
              icon: mdi:tumble-dryer
              template: custom_washer_state_grid_job_state_item_list_items
              entity: '[[[ return variables.ulm_custom_washer_grid_job_state ]]]'
              state:
                - value: 'drying'
                  styles:
                    icon:
                      - transform: scale(1.2)
                      - color: black
                    card:
                      - background-color: 'white'